const { execFileSync } = require('child_process');
const fs = require('fs');
const P = 'assets/data/preset-teams.json';
const raw = execFileSync('git', ['show', '287dd6b:' + P], { encoding: 'utf8', maxBuffer: 20 * 1024 * 1024 });
const orig = JSON.parse(raw);
console.log('从最初提交取到: ' + orig.teams.length + ' 个配队');
fs.writeFileSync(P, JSON.stringify({ teams: orig.teams }, null, 2), 'utf8');
const back = JSON.parse(fs.readFileSync(P, 'utf8'));
console.log('已写入 ' + back.teams.length + ' 个:');
back.teams.forEach((t, i) => console.log('  ' + String(i + 1).padStart(2) + '. ' + t.id.padEnd(7) + ' ' + t.name));
const ids = back.teams.map(t => t.id);
console.log('');
console.log('重复 id: ' + (ids.filter((x, i) => ids.indexOf(x) !== i).join(',') || '无'));
console.log('全部是推荐配队: ' + back.teams.every(t => t.isRecommended === true));
