# Stella Sora - HD asset downloader
# Called by download-hd.bat
$ErrorActionPreference = "SilentlyContinue"
$ProgressPreference = "SilentlyContinue"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $scriptDir
$icon = "https://raw.githubusercontent.com/AutumnVN/ssassets/refs/heads/main/export/assets/assetbundles/icon"
$out = Join-Path $root "assets/img/hd"
foreach ($d in @("head","outfit")) { $p = Join-Path $out $d; if (!(Test-Path $p)) { New-Item -ItemType Directory -Path $p -Force | Out-Null } }
$ok = 0; $fail = 0
function Dl($url, $file) {
  if (Test-Path $file) { $script:ok++; return }
  try {
    Invoke-WebRequest -Uri $url -OutFile $file -TimeoutSec 40 -UseBasicParsing
    if ((Get-Item $file).Length -gt 100) { $script:ok++ } else { Remove-Item $file -Force; $script:fail++ }
  } catch { $script:fail++; Write-Host ("FAIL  " + (Split-Path $file -Leaf)) }
}
Write-Host ""
Write-Host "--- Character portraits (XL): 39 files ---"
Dl "$icon/head/head_15702_XL.webp" (Join-Path $out "head/head_15702_XL.webp")
Dl "$icon/head/head_10302_XL.webp" (Join-Path $out "head/head_10302_XL.webp")
Dl "$icon/head/head_11102_XL.webp" (Join-Path $out "head/head_11102_XL.webp")
Dl "$icon/head/head_11202_XL.webp" (Join-Path $out "head/head_11202_XL.webp")
Dl "$icon/head/head_10702_XL.webp" (Join-Path $out "head/head_10702_XL.webp")
Dl "$icon/head/head_11402_XL.webp" (Join-Path $out "head/head_11402_XL.webp")
Dl "$icon/head/head_10802_XL.webp" (Join-Path $out "head/head_10802_XL.webp")
Dl "$icon/head/head_14102_XL.webp" (Join-Path $out "head/head_14102_XL.webp")
Dl "$icon/head/head_11302_XL.webp" (Join-Path $out "head/head_11302_XL.webp")
Dl "$icon/head/head_11702_XL.webp" (Join-Path $out "head/head_11702_XL.webp")
Dl "$icon/head/head_11002_XL.webp" (Join-Path $out "head/head_11002_XL.webp")
Dl "$icon/head/head_11602_XL.webp" (Join-Path $out "head/head_11602_XL.webp")
Dl "$icon/head/head_14502_XL.webp" (Join-Path $out "head/head_14502_XL.webp")
Dl "$icon/head/head_11902_XL.webp" (Join-Path $out "head/head_11902_XL.webp")
Dl "$icon/head/head_13002_XL.webp" (Join-Path $out "head/head_13002_XL.webp")
Dl "$icon/head/head_12502_XL.webp" (Join-Path $out "head/head_12502_XL.webp")
Dl "$icon/head/head_12702_XL.webp" (Join-Path $out "head/head_12702_XL.webp")
Dl "$icon/head/head_13202_XL.webp" (Join-Path $out "head/head_13202_XL.webp")
Dl "$icon/head/head_13502_XL.webp" (Join-Path $out "head/head_13502_XL.webp")
Dl "$icon/head/head_14202_XL.webp" (Join-Path $out "head/head_14202_XL.webp")
Dl "$icon/head/head_14302_XL.webp" (Join-Path $out "head/head_14302_XL.webp")
Dl "$icon/head/head_14902_XL.webp" (Join-Path $out "head/head_14902_XL.webp")
Dl "$icon/head/head_11502_XL.webp" (Join-Path $out "head/head_11502_XL.webp")
Dl "$icon/head/head_12002_XL.webp" (Join-Path $out "head/head_12002_XL.webp")
Dl "$icon/head/head_15002_XL.webp" (Join-Path $out "head/head_15002_XL.webp")
Dl "$icon/head/head_15802_XL.webp" (Join-Path $out "head/head_15802_XL.webp")
Dl "$icon/head/head_15602_XL.webp" (Join-Path $out "head/head_15602_XL.webp")
Dl "$icon/head/head_13402_XL.webp" (Join-Path $out "head/head_13402_XL.webp")
Dl "$icon/head/head_13302_XL.webp" (Join-Path $out "head/head_13302_XL.webp")
Dl "$icon/head/head_14002_XL.webp" (Join-Path $out "head/head_14002_XL.webp")
Dl "$icon/head/head_16002_XL.webp" (Join-Path $out "head/head_16002_XL.webp")
Dl "$icon/head/head_14702_XL.webp" (Join-Path $out "head/head_14702_XL.webp")
Dl "$icon/head/head_14402_XL.webp" (Join-Path $out "head/head_14402_XL.webp")
Dl "$icon/head/head_15502_XL.webp" (Join-Path $out "head/head_15502_XL.webp")
Dl "$icon/head/head_12602_XL.webp" (Join-Path $out "head/head_12602_XL.webp")
Dl "$icon/head/head_12302_XL.webp" (Join-Path $out "head/head_12302_XL.webp")
Dl "$icon/head/head_11802_XL.webp" (Join-Path $out "head/head_11802_XL.webp")
Dl "$icon/head/head_15902_XL.webp" (Join-Path $out "head/head_15902_XL.webp")
Dl "$icon/head/head_13702_XL.webp" (Join-Path $out "head/head_13702_XL.webp")
Write-Host "--- Disc illustrations: 100 files ---"
Dl "$icon/outfit/outfit_4041.webp" (Join-Path $out "outfit/outfit_4041.webp")
Dl "$icon/outfit/outfit_4030.webp" (Join-Path $out "outfit/outfit_4030.webp")
Dl "$icon/outfit/outfit_2006.webp" (Join-Path $out "outfit/outfit_2006.webp")
Dl "$icon/outfit/outfit_2007.webp" (Join-Path $out "outfit/outfit_2007.webp")
Dl "$icon/outfit/outfit_2008.webp" (Join-Path $out "outfit/outfit_2008.webp")
Dl "$icon/outfit/outfit_3016.webp" (Join-Path $out "outfit/outfit_3016.webp")
Dl "$icon/outfit/outfit_4016.webp" (Join-Path $out "outfit/outfit_4016.webp")
Dl "$icon/outfit/outfit_4037.webp" (Join-Path $out "outfit/outfit_4037.webp")
Dl "$icon/outfit/outfit_4023.webp" (Join-Path $out "outfit/outfit_4023.webp")
Dl "$icon/outfit/outfit_1001.webp" (Join-Path $out "outfit/outfit_1001.webp")
Dl "$icon/outfit/outfit_4033.webp" (Join-Path $out "outfit/outfit_4033.webp")
Dl "$icon/outfit/outfit_4056.webp" (Join-Path $out "outfit/outfit_4056.webp")
Dl "$icon/outfit/outfit_4046.webp" (Join-Path $out "outfit/outfit_4046.webp")
Dl "$icon/outfit/outfit_4028.webp" (Join-Path $out "outfit/outfit_4028.webp")
Dl "$icon/outfit/outfit_4015.webp" (Join-Path $out "outfit/outfit_4015.webp")
Dl "$icon/outfit/outfit_4047.webp" (Join-Path $out "outfit/outfit_4047.webp")
Dl "$icon/outfit/outfit_3019.webp" (Join-Path $out "outfit/outfit_3019.webp")
Dl "$icon/outfit/outfit_4032.webp" (Join-Path $out "outfit/outfit_4032.webp")
Dl "$icon/outfit/outfit_2009.webp" (Join-Path $out "outfit/outfit_2009.webp")
Dl "$icon/outfit/outfit_2003.webp" (Join-Path $out "outfit/outfit_2003.webp")
Dl "$icon/outfit/outfit_3007.webp" (Join-Path $out "outfit/outfit_3007.webp")
Dl "$icon/outfit/outfit_4017.webp" (Join-Path $out "outfit/outfit_4017.webp")
Dl "$icon/outfit/outfit_4040.webp" (Join-Path $out "outfit/outfit_4040.webp")
Dl "$icon/outfit/outfit_2005.webp" (Join-Path $out "outfit/outfit_2005.webp")
Dl "$icon/outfit/outfit_4055.webp" (Join-Path $out "outfit/outfit_4055.webp")
Dl "$icon/outfit/outfit_4059.webp" (Join-Path $out "outfit/outfit_4059.webp")
Dl "$icon/outfit/outfit_2010.webp" (Join-Path $out "outfit/outfit_2010.webp")
Dl "$icon/outfit/outfit_3006.webp" (Join-Path $out "outfit/outfit_3006.webp")
Dl "$icon/outfit/outfit_2001.webp" (Join-Path $out "outfit/outfit_2001.webp")
Dl "$icon/outfit/outfit_3024.webp" (Join-Path $out "outfit/outfit_3024.webp")
Dl "$icon/outfit/outfit_1008.webp" (Join-Path $out "outfit/outfit_1008.webp")
Dl "$icon/outfit/outfit_1003.webp" (Join-Path $out "outfit/outfit_1003.webp")
Dl "$icon/outfit/outfit_4053.webp" (Join-Path $out "outfit/outfit_4053.webp")
Dl "$icon/outfit/outfit_3013.webp" (Join-Path $out "outfit/outfit_3013.webp")
Dl "$icon/outfit/outfit_4018.webp" (Join-Path $out "outfit/outfit_4018.webp")
Dl "$icon/outfit/outfit_4054.webp" (Join-Path $out "outfit/outfit_4054.webp")
Dl "$icon/outfit/outfit_1005.webp" (Join-Path $out "outfit/outfit_1005.webp")
Dl "$icon/outfit/outfit_3022.webp" (Join-Path $out "outfit/outfit_3022.webp")
Dl "$icon/outfit/outfit_3011.webp" (Join-Path $out "outfit/outfit_3011.webp")
Dl "$icon/outfit/outfit_4001.webp" (Join-Path $out "outfit/outfit_4001.webp")
Dl "$icon/outfit/outfit_4007.webp" (Join-Path $out "outfit/outfit_4007.webp")
Dl "$icon/outfit/outfit_3021.webp" (Join-Path $out "outfit/outfit_3021.webp")
Dl "$icon/outfit/outfit_4060.webp" (Join-Path $out "outfit/outfit_4060.webp")
Dl "$icon/outfit/outfit_4027.webp" (Join-Path $out "outfit/outfit_4027.webp")
Dl "$icon/outfit/outfit_4009.webp" (Join-Path $out "outfit/outfit_4009.webp")
Dl "$icon/outfit/outfit_4019.webp" (Join-Path $out "outfit/outfit_4019.webp")
Dl "$icon/outfit/outfit_4024.webp" (Join-Path $out "outfit/outfit_4024.webp")
Dl "$icon/outfit/outfit_4045.webp" (Join-Path $out "outfit/outfit_4045.webp")
Dl "$icon/outfit/outfit_4050.webp" (Join-Path $out "outfit/outfit_4050.webp")
Dl "$icon/outfit/outfit_1004.webp" (Join-Path $out "outfit/outfit_1004.webp")
Dl "$icon/outfit/outfit_4010.webp" (Join-Path $out "outfit/outfit_4010.webp")
Dl "$icon/outfit/outfit_3023.webp" (Join-Path $out "outfit/outfit_3023.webp")
Dl "$icon/outfit/outfit_3009.webp" (Join-Path $out "outfit/outfit_3009.webp")
Dl "$icon/outfit/outfit_4057.webp" (Join-Path $out "outfit/outfit_4057.webp")
Dl "$icon/outfit/outfit_4038.webp" (Join-Path $out "outfit/outfit_4038.webp")
Dl "$icon/outfit/outfit_3003.webp" (Join-Path $out "outfit/outfit_3003.webp")
Dl "$icon/outfit/outfit_3002.webp" (Join-Path $out "outfit/outfit_3002.webp")
Dl "$icon/outfit/outfit_4003.webp" (Join-Path $out "outfit/outfit_4003.webp")
Dl "$icon/outfit/outfit_4002.webp" (Join-Path $out "outfit/outfit_4002.webp")
Dl "$icon/outfit/outfit_4048.webp" (Join-Path $out "outfit/outfit_4048.webp")
Dl "$icon/outfit/outfit_4008.webp" (Join-Path $out "outfit/outfit_4008.webp")
Dl "$icon/outfit/outfit_3018.webp" (Join-Path $out "outfit/outfit_3018.webp")
Dl "$icon/outfit/outfit_4020.webp" (Join-Path $out "outfit/outfit_4020.webp")
Dl "$icon/outfit/outfit_1007.webp" (Join-Path $out "outfit/outfit_1007.webp")
Dl "$icon/outfit/outfit_3012.webp" (Join-Path $out "outfit/outfit_3012.webp")
Dl "$icon/outfit/outfit_3010.webp" (Join-Path $out "outfit/outfit_3010.webp")
Dl "$icon/outfit/outfit_4051.webp" (Join-Path $out "outfit/outfit_4051.webp")
Dl "$icon/outfit/outfit_4011.webp" (Join-Path $out "outfit/outfit_4011.webp")
Dl "$icon/outfit/outfit_4058.webp" (Join-Path $out "outfit/outfit_4058.webp")
Dl "$icon/outfit/outfit_4039.webp" (Join-Path $out "outfit/outfit_4039.webp")
Dl "$icon/outfit/outfit_4005.webp" (Join-Path $out "outfit/outfit_4005.webp")
Dl "$icon/outfit/outfit_1002.webp" (Join-Path $out "outfit/outfit_1002.webp")
Dl "$icon/outfit/outfit_1006.webp" (Join-Path $out "outfit/outfit_1006.webp")
Dl "$icon/outfit/outfit_3025.webp" (Join-Path $out "outfit/outfit_3025.webp")
Dl "$icon/outfit/outfit_4014.webp" (Join-Path $out "outfit/outfit_4014.webp")
Dl "$icon/outfit/outfit_4026.webp" (Join-Path $out "outfit/outfit_4026.webp")
Dl "$icon/outfit/outfit_4043.webp" (Join-Path $out "outfit/outfit_4043.webp")
Dl "$icon/outfit/outfit_4029.webp" (Join-Path $out "outfit/outfit_4029.webp")
Dl "$icon/outfit/outfit_4031.webp" (Join-Path $out "outfit/outfit_4031.webp")
Dl "$icon/outfit/outfit_3014.webp" (Join-Path $out "outfit/outfit_3014.webp")
Dl "$icon/outfit/outfit_4036.webp" (Join-Path $out "outfit/outfit_4036.webp")
Dl "$icon/outfit/outfit_4022.webp" (Join-Path $out "outfit/outfit_4022.webp")
Dl "$icon/outfit/outfit_3020.webp" (Join-Path $out "outfit/outfit_3020.webp")
Dl "$icon/outfit/outfit_4012.webp" (Join-Path $out "outfit/outfit_4012.webp")
Dl "$icon/outfit/outfit_4052.webp" (Join-Path $out "outfit/outfit_4052.webp")
Dl "$icon/outfit/outfit_4049.webp" (Join-Path $out "outfit/outfit_4049.webp")
Dl "$icon/outfit/outfit_3008.webp" (Join-Path $out "outfit/outfit_3008.webp")
Dl "$icon/outfit/outfit_3004.webp" (Join-Path $out "outfit/outfit_3004.webp")
Dl "$icon/outfit/outfit_4021.webp" (Join-Path $out "outfit/outfit_4021.webp")
Dl "$icon/outfit/outfit_3015.webp" (Join-Path $out "outfit/outfit_3015.webp")
Dl "$icon/outfit/outfit_4044.webp" (Join-Path $out "outfit/outfit_4044.webp")
Dl "$icon/outfit/outfit_3026.webp" (Join-Path $out "outfit/outfit_3026.webp")
Dl "$icon/outfit/outfit_4013.webp" (Join-Path $out "outfit/outfit_4013.webp")
Dl "$icon/outfit/outfit_2002.webp" (Join-Path $out "outfit/outfit_2002.webp")
Dl "$icon/outfit/outfit_4042.webp" (Join-Path $out "outfit/outfit_4042.webp")
Dl "$icon/outfit/outfit_4004.webp" (Join-Path $out "outfit/outfit_4004.webp")
Dl "$icon/outfit/outfit_4006.webp" (Join-Path $out "outfit/outfit_4006.webp")
Dl "$icon/outfit/outfit_3001.webp" (Join-Path $out "outfit/outfit_3001.webp")
Dl "$icon/outfit/outfit_3005.webp" (Join-Path $out "outfit/outfit_3005.webp")
Dl "$icon/outfit/outfit_3017.webp" (Join-Path $out "outfit/outfit_3017.webp")

Write-Host ""
Write-Host "========================================"
Write-Host ("  DONE.  ok=" + $ok + "  fail=" + $fail)
Write-Host ("  " + $out)
Write-Host "  Tell the assistant when finished."
Write-Host "========================================"
